Algoritmo "AREA-TRIANGULO"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama 
// Descrição   : Calcula a área de um triângulo
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 24/08/2021
Var

  base, altura, area : real

Inicio

Escreva("Digite o valor da base do triângulo (em cm):")
Leia(base)

Escreva("Digite o valor da altura do triângulo (em cm):")
Leia(altura)

area <- (base * altura) / 2

Escreva("A área do triângulo é de:", area, "cm²")

Fimalgoritmo