Algoritmo "AREA-RETANGULO"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Calcula a área de um retangulo
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 24/08/2021
Var

  base, altura, area : real

Inicio

Escreva("Digite o valor da base do retângulo (em cm):")
Leia(base)

Escreva("Digite o valor da altura do retângulo (em cm):")
Leia(altura)

area <- base * altura

Escreva("A área do retângulo é de:", area, "cm²")

Fimalgoritmo