Algoritmo "AREA-QUADRADO"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Calcula a área de um quadrado
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 24/08/2021
Var

  lado, area : real

Inicio

Escreva("Digite o valor de um dos lados do quadrado (em cm):")
Leia(lado)

area <- lado*lado

Escreva("A área do quadrado é de:", area, "cm²")

Fimalgoritmo