Algoritmo "AREA-CIRCULO"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Calcula a área de um circulo
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 24/08/2021
Var

  r, area : real

Inicio

Escreva("Digite o valor do raio do círculo (em cm):")
Leia(r)

area <- (r*r) * pi  // (r**2) * pi

Escreva("A área do círculo é de:", area:2:1, "cm²")

Fimalgoritmo