Algoritmo "CONDIÇÃO-POSITIVO"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama

// Descrição   : Ler um valor e escrever se é positivo ou negativo (considere o valor zero como positivo).

// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 26/08/2021
Var

   valor : inteiro

Inicio

   Escreval("Digite um valor: ")
   Leia(valor)

   se (valor>=0) entao
      Escreva("O valor é POSITIVO !")
   senao
      Escreva("O valor é NEGATIVO !")
   fimse

Fimalgoritmo