Algoritmo "DESAFIO-2"
// Disciplina  : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100). ps: não vale usar GAUSS
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 01/09/2021
Var

   i, total : inteiro

Inicio

   enquanto i < 101 faca
      total <- total + i
      i <- i + 1
   fimenquanto
   
Escreva("Total da soma: ", total, i)

Fimalgoritmo