Algoritmo "DESAFIO-1"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 01/09/2021

Var

   v, i : inteiro

Inicio

   Escreva("Digite um valor: ")
   Leia(v)

   enquanto i < 10 faca
      i <- i+1
      Escreval(v, " x", i, " =", i * v)
   fimenquanto

Fimalgoritmo