Algoritmo "EX-05"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Exercico para treino de lógica de programação
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 03/09/2021

Var

   c, n : inteiro

Inicio

   enquanto c < 15 faca
   
      se n = 0 entao
         Escreval(1)
         n <- 3
      senao
         n <- n * 3
      fimse
      
      Escreval(n)
      c <- c + 1
   fimenquanto

Fimalgoritmo