Algoritmo "EXEMPLO-PARA01"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : exemplos
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 03/09/2021
Var

   cont, numero:inteiro

Inicio

   Escreval("Digite um número :")
   Leia(numero)
   
   para cont de 1 ate 10 passo 1 faca
      Escreval(numero," * ",cont, " = ", numero*cont)
   fimpara

Fimalgoritmo