Algoritmo "EXEMPLO-PARA02"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : exemplos
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 03/09/2021
Var

   contH, contM, contS : inteiro

Inicio

   para contH de 0 ate 24 faca
      para contM de 0 ate 59 faca
         para contS de 0 ate 59 faca
            Escreval(contH, " :", contM, " :", contS)
            timer 500
         fimpara
      fimpara
   fimpara

Fimalgoritmo