Algoritmo "Exercicio-1-muitos"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : João Pedro Mendes Gomes
// Data atual  : 03/09/2021
Var

   i, n : inteiro

Inicio

   para i de 1 ate 100 passo 1 faca

      n <- i + n

   fimpara

   escreval("Resultado:", n)

Fimalgoritmo