Algoritmo "Soma"
// Disciplina   : [Lógica de Programação e JS]
// Professor   : Obama
// Descrição   : Soma de dois valores e apresenta no terminal
// Autor(a)    : João Pedro M. Gomes
// Data atual  : 24/08/2021
Var

n1, n2, result : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval("Digite um valor:")
Leia(n1)

Escreval("Digite outrovalor:")
Leia(n2)

result <- n1+n2

Escreva("Soma:", result)


Fimalgoritmo